name: CI

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-and-push:
    name: "Build, Bump and Push"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          PRERELEASE: false

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./broker-service.dockerfile
          push: true
          tags: |
            sunnygosdk/sunnygo-broker:${{ steps.tag_version.outputs.new_tag }}
            sunnygosdk/sunnygo-broker:latest
